In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Student Social Media And Mental Health Impact.csv")

In [4]:
df.head()

,Age,Gender,Country,Academic_Level,Most_Used_Platform,Purpose_Of_Use,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Stress_Level,Mental_Health_Score
0,21,Male,Other,Undergraduate,Facebook,Networking,4.0,134,4.5,2.2,6.7,Medium,6.8
1,23,Female,Other,Graduate,LinkedIn,Education,1.6,73,7.0,2.4,8.6,Low,7.6
2,22,Male,Canada,Undergraduate,Instagram,Entertainment,4.6,166,4.0,1.8,6.7,Medium,7.0
3,18,Male,Other,High School,Snapchat,Entertainment,7.0,220,1.0,1.7,5.4,Very High,5.3
4,24,Female,Other,Graduate,Facebook,Networking,7.5,237,1.0,1.1,5.0,Very High,4.4

In [5]:
df.shape

(5000, 13)

In [6]:
df.isnull().sum()

Age                        0
Gender                     0
Country                    0
Academic_Level             0
Most_Used_Platform         0
Purpose_Of_Use             0
Avg_Daily_Usage_Hours      0
Daily_Unlocks              0
Study_Hours                0
Physical_Activity_Hours    0
Sleep_Hours_Per_Night      0
Stress_Level               0
Mental_Health_Score        0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      5000 non-null   int64
 1   Gender                   5000 non-null   object
 2   Country                  5000 non-null   object
 3   Academic_Level           5000 non-null   object
 4   Most_Used_Platform       5000 non-null   object
 5   Purpose_Of_Use           5000 non-null   object
 6   Avg_Daily_Usage_Hours    5000 non-null   float64
 7   Daily_Unlocks            5000 non-null   int64
 8   Study_Hours              5000 non-null   float64
 9   Physical_Activity_Hours  5000 non-null   float64
 10  Sleep_Hours_Per_Night    5000 non-null   float64
 11  Stress_Level             5000 non-null   object
 12  Mental_Health_Score      5000 non-null   float64
dtypes: float64(5), int64(2), object(6)
memory usage: 507.9+ KB

In [8]:
df.duplicated().sum()

np.int64(2)

In [9]:
df = df.drop_duplicates()

In [10]:
df.shape

(4998, 13)

In [11]:
df.describe()

,Age,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Mental_Health_Score
count,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000
mean,20.822129,5.078491,171.455582,3.008403,1.750760,6.634654,6.231152
std,1.736774,1.654097,42.859829,1.636831,0.668406,1.221561,1.278476
min,18.000000,1.000000,62.000000,0.300000,-0.400000,3.600000,3.600000
25%,19.000000,3.800000,140.000000,1.500000,1.300000,5.600000,5.100000
50%,21.000000,5.000000,171.000000,2.800000,1.700000,6.600000,6.100000
75%,22.000000,6.300000,204.000000,4.200000,2.200000,7.500000,7.100000
max,24.000000,8.800000,273.000000,8.300000,4.100000,9.900000,9.400000

In [12]:
df['Physical_Activity_Hours'] = df['Physical_Activity_Hours'].clip(lower=0)

In [13]:
df.describe()

,Age,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Mental_Health_Score
count,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000
mean,20.822129,5.078491,171.455582,3.008403,1.751160,6.634654,6.231152
std,1.736774,1.654097,42.859829,1.636831,0.667282,1.221561,1.278476
min,18.000000,1.000000,62.000000,0.300000,0.000000,3.600000,3.600000
25%,19.000000,3.800000,140.000000,1.500000,1.300000,5.600000,5.100000
50%,21.000000,5.000000,171.000000,2.800000,1.700000,6.600000,6.100000
75%,22.000000,6.300000,204.000000,4.200000,2.200000,7.500000,7.100000
max,24.000000,8.800000,273.000000,8.300000,4.100000,9.900000,9.400000

In [14]:
num_cols = df.select_dtypes(include='number')
num_cols.skew()

Age                        0.155008
Avg_Daily_Usage_Hours      0.005575
Daily_Unlocks              0.002309
Study_Hours                0.436125
Physical_Activity_Hours    0.053288
Sleep_Hours_Per_Night      0.123919
Mental_Health_Score        0.207086
dtype: float64

In [15]:
df.columns

Index(['Age', 'Gender', 'Country', 'Academic_Level', 'Most_Used_Platform',
       'Purpose_Of_Use', 'Avg_Daily_Usage_Hours', 'Daily_Unlocks',
       'Study_Hours', 'Physical_Activity_Hours', 'Sleep_Hours_Per_Night',
       'Stress_Level', 'Mental_Health_Score'],
      dtype='object')

In [16]:
ord_col = df.select_dtypes(include='object')
ord_col['Country'].nunique()

111

In [17]:
counts = df['Country'].value_counts()

threshold = 100 

repl = counts[counts<=threshold].index

df['Country'] = df['Country'].replace(repl,'Other')

In [18]:
skew_col = ['Study_Hours']

numeric_cols = ['Age','Avg_Daily_Usage_Hours','Daily_Unlocks','Physical_Activity_Hours','Sleep_Hours_Per_Night']

ordinal_cols = ['Academic_Level','Stress_Level']

nominal_cols = ['Gender','Country','Most_Used_Platform','Purpose_Of_Use']

features = skew_col + numeric_cols + ordinal_cols + nominal_cols
x = df[features]
y = df['Mental_Health_Score']

In [19]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [20]:
from sklearn.preprocessing import StandardScaler, FunctionTransformer, OrdinalEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

study_hours_pipeline = Pipeline(steps=[
    ('log_transform', FunctionTransformer(np.log1p)),
    ('scaler', StandardScaler())
])

preprocessing = ColumnTransformer(transformers=[
    ('study_hours', study_hours_pipeline, skew_col),
    ('numer',StandardScaler(),numeric_cols),
    ('ordinal',OrdinalEncoder(categories=[['High School', 'Undergraduate', 'Graduate'],['Low', 'Medium', 'High', 'Very High']]),ordinal_cols),
    ('nominal',OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32),nominal_cols)
])

In [21]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

rf_pipeline = Pipeline(steps=[
                       ('preprocessing',preprocessing),
                       ('regression',RandomForestRegressor())
])

In [31]:
rf_pipeline.fit(x_train, y_train)

rf_pred_test = rf_pipeline.predict(x_test)
rf_pred_train = rf_pipeline.predict(x_train)

r2_test = r2_score(y_test,rf_pred_test)
r2_train = r2_score(y_train,rf_pred_train)
mae_score = mean_absolute_error(y_test, rf_pred_test)

print(f"Accuracy of Training {r2_train}")
print(f"Accuracy of Testing {r2_test}")
print(f'MAE {mae_score}')

Accuracy of Training 0.9823637653659935
Accuracy of Testing 0.8860468414176023
MAE 0.33341756666666683

In [24]:
testing_accuracy = mean_squared_error(y_test,rf_pred_test)
traning_accuracy = mean_squared_error(y_train,rf_pred_train)
print(f"MSE of Training {traning_accuracy}")
print(f"MSE of Testing {testing_accuracy}")

MSE of Training 0.02821830200712004
MSE of Testing 0.2080647603958335

In [25]:
testing_accuracy = np.sqrt(mean_squared_error(y_test,rf_pred_test))
traning_accuracy = np.sqrt(mean_squared_error(y_train,rf_pred_train))
print(f"RMSE of Training {traning_accuracy}")
print(f"RMSE of Testing {testing_accuracy}")

RMSE of Training 0.16798304083186505
RMSE of Testing 0.45614116279484523

In [32]:
print('Adjusted R2_Score', 1 - ((1-r2_test)*(40-1)/(40-1-1)))

Adjusted R2_Score 0.8830480740864866