In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('house-train.csv',usecols=['GarageQual','FireplaceQu', 'SalePrice'])

In [4]:
df.head()

  FireplaceQu GarageQual  SalePrice
0         NaN         TA     208500
1          TA         TA     181500
2          TA         TA     223500
3          Gd         TA     140000
4          TA         TA     250000

In [5]:
df.isnull().sum()

FireplaceQu    690
GarageQual      81
SalePrice        0
dtype: int64

In [6]:
x = df.drop(columns='SalePrice')
y = df['SalePrice']

In [7]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)
x_train

     FireplaceQu GarageQual
455           TA         TA
863          NaN         TA
504           Fa         TA
1413          Gd         TA
1389          Gd         TA
...          ...        ...
466           Po         TA
299           Gd         TA
493           Fa         TA
527           Gd         TA
1192         NaN         TA

[1168 rows x 2 columns]

In [8]:
for col in x_train.columns:
    np.random.seed(42)
    x_train[f'{col}_imputed'] = x_train[col]
    non_missing_values = x_train[col].dropna().values    
    missing_indices = x_train[col].isnull()
    x_train.loc[missing_indices, f'{col}_imputed'] = np.random.choice(non_missing_values, size=missing_indices.sum())

In [9]:
x_train.sample(5)

     FireplaceQu GarageQual FireplaceQu_imputed GarageQual_imputed
189           Gd         TA                  Gd                 TA
682           Gd         TA                  Gd                 TA
994           Gd         TA                  Gd                 TA
1362          Gd         TA                  Gd                 TA
382          NaN         TA                  Gd                 TA