In [1]:
import numpy as np
import pandas as pd

In [18]:
df = pd.read_csv('adult.csv',usecols=[5,6,7,8,9,12,14])

In [19]:
df.sample(5)

,marital.status,occupation,relationship,race,sex,hours.per.week,income
5463,Never-married,Adm-clerical,Not-in-family,White,Female,40,<=50K
15476,Married-civ-spouse,Exec-managerial,Husband,White,Male,60,<=50K
9274,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,<=50K
2285,Divorced,Prof-specialty,Not-in-family,White,Female,33,>50K
9733,Never-married,Adm-clerical,Own-child,White,Male,40,<=50K

In [62]:
df['occupation'].value_counts()

occupation
Prof-specialty       4140
Craft-repair         4099
Exec-managerial      4066
Adm-clerical         3770
Sales                3650
Other-service        3295
Machine-op-inspct    2002
?                    1843
Transport-moving     1597
Handlers-cleaners    1370
Farming-fishing       994
Tech-support          928
Protective-serv       649
Priv-house-serv       149
Armed-Forces            9
Name: count, dtype: int64

# Train test split

In [27]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop(columns='income'), df['income'],test_size=0.2,random_state=0)
x_train.shape, x_test.shape

((26048, 6), (6513, 6))

# One Hot Encoder

In [52]:
counts1 = df['marital.status'].value_counts()
counts2 = df['occupation'].value_counts()
counts =pd.concat((counts1, counts2))
threshold=1000
repl=counts[counts<=threshold].index
pd.get_dummies(x_train[['marital.status','occupation']].replace(repl,'uncommnon'))
#pd.get_dummies(x_train[['occupation']].replace(repl,'uncommnon'))

,marital.status_Divorced,marital.status_Married-civ-spouse,marital.status_Never-married,marital.status_Separated,marital.status_uncommnon,occupation_?,occupation_Adm-clerical,occupation_Craft-repair,occupation_Exec-managerial,occupation_Handlers-cleaners,occupation_Machine-op-inspct,occupation_Other-service,occupation_Prof-specialty,occupation_Sales,occupation_Transport-moving,occupation_uncommnon
15282,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False
24870,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False
18822,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False
26404,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False
7842,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13123,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
19648,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False
9845,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False
10799,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False
2732,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False

In [57]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

x_train_new = ohe.fit_transform(x_train[['marital.status','occupation','relationship','sex','race']].replace(repl,'other'))
x_test_new = ohe.fit_transform(x_test[['marital.status','occupation','relationship','sex','race']].replace(repl,'other'))

In [58]:
x_train_new.shape

(26048, 24)

In [66]:
np.hstack((x_train[['hours.per.week']].values,x_train_new)).shape
np.hstack((x_test[['hours.per.week']].values,x_test_new)).shape

(6513, 25)