In [128]:
import numpy as np
import pandas as pd

In [129]:
df = pd.DataFrame()

In [130]:
df['X1'] = [1,2,3,4,5,6,6,7,9,9]
df['X2'] = [5,3,6,8,1,9,5,8,9,2]
df['label'] = [1,1,0,1,0,1,0,1,0,0]

In [131]:
df

   X1  X2  label
0   1   5      1
1   2   3      1
2   3   6      0
3   4   8      1
4   5   1      0
5   6   9      1
6   6   5      0
7   7   8      1
8   9   9      0
9   9   2      0

In [132]:
X = df.drop(columns=['label'])
y = df['label']

In [133]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [134]:
X_train

   X1  X2
5   6   9
0   1   5
7   7   8
2   3   6
9   9   2
4   5   1
3   4   8
6   6   5

In [135]:
from sklearn.ensemble import AdaBoostClassifier

In [136]:
abc = AdaBoostClassifier(n_estimators=50)
abc.fit(X_train,y_train)
y_pred = abc.predict(X_test)

In [140]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5

In [141]:
abc2 = mera(n_estimator=50)

abc2.fit(X_train,y_train)

C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))
C:\Users\cccc\AppData\Local\Temp\ipykernel_8216\2607669261.py:19: RuntimeWarning: divide by zero encountered in log
  alpha = 0.5*np.log((1-error)/(error+00000.1))

In [139]:
class mera:

    def __init__(self,base_estimator=DecisionTreeClassifier(max_depth=1), n_estimator=50):
        self.base_estimator = base_estimator
        self.n_estimator = n_estimator
        self.alphas = []
        self.models = []

    def fit(self,x_train,y_train):
        for i in range(self.n_estimator):
            weight = np.ones(X_train.shape[0])/X_train.shape[0]

            self.base_estimator.fit(X_train,y_train,sample_weight=weight)

            y_pred = self.base_estimator.predict(X_train)

            error = np.sum(y_pred != y_train)

            alpha = 0.5*np.log((1-error)/(error+00000.1))

            self.models.append(self.base_estimator) 
            self.alphas.append(alpha)
            
            for i in range(len(y_pred)):
                if y_train.values[i] == y_pred[i]:
                    weight[i] = weight[i] * np.exp(-0.432)
                else:
                    weight[i] = weight[i] * np.exp(0.432)

            weight /= np.sum(weight)


    def predict(self,x_test):
        prediction = np.zeros(X_test.shape[0])  

        for model, alpha in zip(self.models, self.alphas):
            model_pred = model.predict(X_test)  
            prediction += alpha * model_pred  

        return np.sign(prediction)

In [ ]:
.astype(int)

In [ ]:
class mera:

    def __init__(self,base_estimator=DecisionTreeClassifier(max_depth=1), n_estimator=50):
        self.base_estimator = base_estimator
        self.n_estimator = n_estimator
        #self.learning_rate = learning_rate

    def fit(self, x_train,y_train):
        for i in range(n_estimator):
            weight = np.ones(X_train.shape[o])/X_train.shape[0]

            base_estimator.fit(X_train,y_train)

            y_pred = base_estimator.predict(X)

            error = 0
            for i in range(len(y_pred)):
                if y_train.values[i] != y_pred[i]:
                    error += 1

            alpha = 0.5*np.log((1-error)/(error))