In [41]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import scipy.stats as stats

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LinearRegression

from sklearn.metrics import r2_score

from sklearn.preprocessing import PowerTransformer

In [52]:
df = pd.read_csv('train.csv',usecols=[1,5,9])

In [53]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [54]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

C:\Users\Saqib Ali\AppData\Local\Temp\ipykernel_15972\694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

In [55]:
df.isnull().sum()

Survived    0
Age         0
Fare        0
dtype: int64

In [61]:
df.describe()

         Survived         Age        Fare
count  891.000000  891.000000  891.000000
mean     0.383838   29.699118   32.204208
std      0.486592   13.002015   49.693429
min      0.000000    0.420000    0.000000
25%      0.000000   22.000000    7.910400
50%      0.000000   29.699118   14.454200
75%      1.000000   35.000000   31.000000
max      1.000000   80.000000  512.329200

In [56]:
x = df.iloc[:,1:3]
y = df.iloc[:,-1]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [57]:
# Model training Before Power_Transformer

In [58]:
lr = LinearRegression()

lr.fit(x_train ,y_train)

y_pred = lr.predict(x_test)

r2_score(y_test,y_pred)

1.0

In [59]:
np.mean(cross_val_score(lr, x, y, scoring="r2"))

1.0

In [ ]:
# Power_Transformer[box_cox]

In [64]:
pt = PowerTransformer(method='box-cox')

x_train_transformed = pt.fit_transform(x_train+0.000000001)
x_test_transformed = pt.fit_transform(x_test+0.000000001)

pd.DataFrame({'col':x_train.columns,'Lambdas':pt.lambdas_})

    col   Lambdas
0   Age  0.666541
1  Fare  0.231497

In [ ]:
# model training After Power_Transformation[box-cox]

In [66]:
lr = LinearRegression()

lr.fit(x_train_transformed ,y_train)

y_pred2 = lr.predict(x_test_transformed)

r2_score(y_test,y_pred2)

0.6955527862587114

In [72]:
x_transformed = pt.fit_transform(x+0.00000000001)
np.mean(cross_val_score(lr, x_transformed, y, scoring="r2"))

0.6633655079341617

In [ ]:
# Power_Transformer[Yeo-Johnson]

In [69]:
pt1 = PowerTransformer()

x_train_transformed2 = pt1.fit_transform(x_train)
x_test_transformed2 = pt1.fit_transform(x_test)

pd.DataFrame({'col':x_train.columns,'Lambdas':pt1.lambdas_})

    col   Lambdas
0   Age  0.643452
1  Fare -0.108208

In [ ]:
# Model Training After Power_Transformation[Yeo-JohnSon]

In [70]:
lr = LinearRegression()

lr.fit(x_train_transformed2 ,y_train)

y_pred3 = lr.predict(x_test_transformed2)

r2_score(y_test,y_pred3)

0.6133587476551978

In [73]:
x_transformed2 = pt1.fit_transform(x)
np.mean(cross_val_score(lr, x_transformed2, y, scoring="r2"))

0.5658083677289658

In [74]:
# Side by Side Comparsion of boc-cox & Yeo-Johnson Lambdas
pd.DataFrame({'col':x_train.columns,'box-cox_lambda':pt.lambdas_, 'Yeo-johnson_Lambdas':pt1.lambdas_})

    col  box-cox_lambda  Yeo-johnson_Lambdas
0   Age        0.822982             0.819744
1  Fare        0.225477            -0.097787