In [37]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator,SimpleImputer

In [38]:
df = pd.read_csv('data_science_job.csv',usecols=[8,11,12])

In [39]:
df.head()

   experience  training_hours  target
0        20.0            36.0     1.0
1        15.0            47.0     0.0
2         5.0            83.0     0.0
3         0.0            52.0     1.0
4        20.0             8.0     0.0

In [40]:
x = df.drop(columns=['target'])
y = df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [36]:
mi = MissingIndicator()

mi.fit(x_train)

x_train_missing = mi.transform(x_train)
x_test_missing = mi.transform(x_test)

In [12]:
x_train_missing

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [26]:
x_test_missing

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [24]:
print(x_train.shape)
print(x_test.shape)
print(x_train_missing[0].shape)
print(x_test_missing[0].shape)

(15326, 2)
(3832, 2)
(2,)
(2,)

In [27]:
x_train['experience_na'] = x_train_missing[:,0]
x_test['experience_na'] = x_test_missing[:,0] 

x_train['training_hours_na'] = x_train_missing[:,1]
x_test['training_hours_na'] = x_test_missing[:,1]

In [28]:
x_train.sample(5)

       experience  training_hours  experience_na  training_hours_na
7707         15.0             8.0          False              False
12383         0.0             NaN          False               True
5653         20.0            36.0          False              False
9360          4.0            18.0          False              False
11937         5.0            26.0          False              False

In [41]:
si = SimpleImputer(add_indicator=True)

x_train = si.fit_transform(x_train)
x_test = si.transform(x_test)

In [42]:
x_train

array([[  2., 134.,   0.,   0.],
       [  8.,  58.,   0.,   0.],
       [  7., 206.,   0.,   0.],
       ...,
       [ 20., 120.,   0.,   0.],
       [  7.,  48.,   0.,   0.],
       [  4.,  74.,   0.,   0.]])