In [137]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [128]:
df = pd.read_csv('train.csv').drop(columns=['Name','SibSp','Parch','Ticket','Cabin','PassengerId','Sex','Embarked'])

In [129]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [130]:
df.isnull().sum()

Survived      0
Pclass        0
Age         177
Fare          0
dtype: int64

In [131]:
x = df.drop(columns='Survived')
y = df['Survived']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [132]:
x_train

     Pclass   Age      Fare
331       1  45.5   28.5000
733       2  23.0   13.0000
382       3  32.0    7.9250
704       3  26.0    7.8542
813       3   6.0   31.2750
..      ...   ...       ...
106       3  21.0    7.6500
270       1   NaN   31.0000
860       3  41.0   14.1083
435       1  14.0  120.0000
102       1  21.0   77.2875

[712 rows x 3 columns]

In [133]:
si = SimpleImputer()

x_train_trf = si.fit_transform(x_train[['Age']])
x_test_trf = si.transform(x_test[['Age']])

In [135]:
lr = LogisticRegression()

lr.fit(x_train_trf,y_train)

y_pred2 = lr.predict(x_test_trf)

accuracy_score(y_pred2,y_test)

0.5865921787709497

In [142]:
it = IterativeImputer(max_iter=10,random_state=0)

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [143]:
lr = LogisticRegression()

lr.fit(x_train_trf2,y_train)

y_pred = lr.predict(x_test_trf2)

accuracy_score(y_pred,y_test)

0.7374301675977654