In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('customer.csv')

In [4]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [5]:
df = df.iloc[:,2:]

In [6]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

# Train Test Split

In [9]:
x = df.iloc[:,:-1]
x.sample(5)

     review education
13  Average    School
2      Good        PG
39     Poor        PG
22     Poor        PG
0   Average    School

In [12]:
y = df['purchased']
y.sample(5)

13     No
48    Yes
20    Yes
25     No
7     Yes
Name: purchased, dtype: object

In [26]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [27]:
x_train.head()

     review education
7      Poor    School
14     Poor        PG
45     Poor        PG
48     Good        UG
29  Average        UG

# Ordinal Encoder

In [28]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

oe.fit(x_train)

x_train_transformed = oe.transform(x_train)
x_test_transformed = oe.transform(x_test)

In [29]:
x_train_transformed = pd.DataFrame(x_train_transformed, columns=x_train.columns)
x_test_transformed = pd.DataFrame(x_test_transformed, columns=x_test.columns)

In [30]:
x_train_transformed.head()

   review  education
0     0.0        0.0
1     0.0        2.0
2     0.0        2.0
3     2.0        1.0
4     1.0        1.0

In [31]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

# Label Encoder

In [33]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(y_train)

y_train_transformed = le.transform(y_train)
y_test_transformed = le.transform(y_test)

In [35]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [39]:
y_train_transformed

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])