In [51]:
import numpy as np
import pandas as pd

import plotly.express as px
import plotly.graph_objects as po

from sklearn.metrics import r2_score

In [52]:
df = pd.read_csv('daily-website-visitors.csv',usecols=[4,5,6,7])

In [53]:
df.head()

  Page.Loads Unique.Visits First.Time.Visits Returning.Visits
0      2,146         1,582             1,430              152
1      3,621         2,528             2,297              231
2      3,698         2,630             2,352              278
3      3,667         2,614             2,327              287
4      3,316         2,366             2,130              236

In [58]:
for i in df.columns:
    df[i] = df[i].str.replace(',','.').astype(float)

In [59]:
df.head()

   Page.Loads  Unique.Visits  First.Time.Visits  Returning.Visits
0       2.146          1.582              1.430             152.0
1       3.621          2.528              2.297             231.0
2       3.698          2.630              2.352             278.0
3       3.667          2.614              2.327             287.0
4       3.316          2.366              2.130             236.0

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2167 entries, 0 to 2166
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Page.Loads         2167 non-null   float64
 1   Unique.Visits      2167 non-null   float64
 2   First.Time.Visits  2167 non-null   float64
 3   Returning.Visits   2167 non-null   float64
dtypes: float64(4)
memory usage: 67.8 KB

In [61]:
x = df.iloc[:,1:]
y = df['Page.Loads']

In [62]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=3)

In [64]:
(x_train).head()

      Unique.Visits  First.Time.Visits  Returning.Visits
568           4.216              3.426             790.0
222           3.387              2.845             542.0
811           2.667              2.178             489.0
1979          2.949              2.529             420.0
1825          2.508              2.121             387.0

In [65]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
r2_score(y_test,y_pred)

0.8293820665144362

In [66]:
lr.coef_

array([-0.00019919, -0.00050427,  0.00706784])

In [67]:
lr.intercept_

np.float64(0.523098467826888)