In [72]:
import numpy as np
import pandas as pd

In [73]:
df = pd.read_csv('train.csv')

In [74]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [75]:
df = df.drop(columns=['PassengerId','Name','Ticket','Cabin'])

In [76]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [77]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(df.drop(columns='Survived'),df['Survived'],test_size=0.2)

x_train.shape,y_train.shape

((712, 7), (712,))

In [78]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [79]:
# Without Transformer

In [80]:
# SimpleImputer -> Age & Embarak
from sklearn.impute import SimpleImputer

si = SimpleImputer()
si1 = SimpleImputer(strategy='most_frequent')

x_train_Age = si.fit_transform(x_train[['Age']])
x_test_Age = si.transform(x_test[['Age',]])

x_train_Embarked = si1.fit_transform(x_train[['Embarked']])
x_test_Embarked = si1.transform(x_test[['Embarked']])
x_train_Age.shape
x_train_Embarked.shape

(712, 1)

In [81]:
# StandardScaler -> Age & Fare
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler1 = StandardScaler()

x_train_Age = scaler.fit_transform(x_train_Age)
x_test_Age = si.transform(x_test_Age)

x_train_Fare = si1.fit_transform(x_train[['Fare']])
x_test_Fare = si1.transform(x_test[['Fare']])
x_train_Age.shape
x_train_Fare.shape

E:\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(

(712, 1)

In [82]:
# OneHotEncoder -> Sex & Embarked
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first',sparse_output=False)
ohe1 = OneHotEncoder(drop='first',sparse_output=False)

x_train_Sex = ohe.fit_transform(x_train[['Sex']])
x_test_Sex = ohe.transform(x_test[['Sex']])

x_train_Embarked = ohe1.fit_transform(x_train[['Embarked']])
x_test_Embarked = ohe1.transform(x_test[['Embarked']])
x_train_Sex.shape
x_train_Embarked.shape

(712, 3)

In [87]:
#Extract remaining features

x_train_rem = x_train.drop(['Age','Embarked','Fare','Sex'],axis=1)
x_test_rem = x_test.drop(['Age','Embarked','Fare','Sex'],axis=1)

In [88]:
# Concatenate them back all
x_train_transformed = np.concatenate((x_train_Age,x_train_Fare,x_train_Sex,x_train_Embarked,x_train_rem),axis=1)
x_test_transformed = np.concatenate((x_test_Age,x_test_Fare,x_test_Sex,x_test_Embarked,x_test_rem),axis=1)

In [89]:
x_train_transformed.shape

(712, 9)

In [85]:
# With Transformer
from sklearn.compose import ColumnTransformer

Transformer = ColumnTransformer(transformers=[
    ('trf1',SimpleImputer(),[3]),
    ('trf2',SimpleImputer(strategy='most_frequent'),[7]),
    ('trf3',StandardScaler(),[3,6]),
    ('trf4',OneHotEncoder(drop='first',sparse_output=False),[2,7]),
])