In [1]:
import numpy as np 
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working With Date

In [7]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [11]:
# Extract Year
date['date_year'] = date['date'].dt.year

In [12]:
date.sample(5)

          date  product_id  city_id  orders  date_year
366 2019-07-22        2307        4       6       2019
117 2019-05-20        1556       17       2       2019
902 2019-03-24        5031        0       6       2019
131 2019-04-16        7296       22      11       2019
550 2019-07-05        5115        2     121       2019

In [15]:
# Extract Month
date['date_month_num'] = date['date'].dt.month

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_num
458,2019-08-02,5742,26,1,2019,8,2,8
406,2018-11-20,1081,22,1,2018,11,20,11
825,2019-03-25,4691,14,1,2019,3,25,3
740,2019-08-05,709,16,220,2019,8,5,8
110,2019-08-13,7059,14,11,2019,8,13,8

In [16]:
# Extract Month
date['date_month_name'] = date['date'].dt.month_name()

date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_num,date_month_name
545,2019-01-21,5280,23,3,2019,1,21,1,January
86,2019-06-27,3904,1,29,2019,6,27,6,June
295,2018-10-29,3012,18,3,2018,10,29,10,October
988,2019-02-03,5022,2,43,2019,2,3,2,February
236,2018-08-24,4576,22,3,2018,8,24,8,August

In [28]:
# Extract Day
date['date_day'] = date['date'].dt.day

#date = date.drop(columns=['product_id','city_id','date_month'])
date.sample(5)

,date,orders,date_year,date_day,date_month_num,date_month_name,date_dayofweek
694,2019-06-26,1,2019,26,6,June,2
524,2019-12-01,7,2019,1,12,December,6
972,2019-11-08,6,2019,8,11,November,4
518,2018-07-26,15,2018,26,7,July,3
962,2018-09-10,99,2018,10,9,September,0

In [30]:
# Extract Day_of_week
date['date_dayofweek'] = date['date'].dt.dayofweek

date.sample(5)

,date,orders,date_year,date_day,date_month_num,date_month_name,date_dayofweek
170,2019-03-25,5,2019,25,3,March,0
712,2019-02-10,8,2019,10,2,February,6
962,2018-09-10,99,2018,10,9,September,0
567,2019-11-15,24,2019,15,11,November,4
687,2019-10-13,4,2019,13,10,October,6

In [35]:
# Extract Day_of_week -> name
date['date_dow_name'] = date['date'].dt.day_name()

date.sample(5)

,date,orders,date_year,date_day,date_month_num,date_month_name,date_dayofweek,date_dow_name
805,2019-11-28,7,2019,28,11,November,3,Thursday
412,2018-10-10,1,2018,10,10,October,2,Wednesday
64,2019-06-01,5,2019,1,6,June,5,Saturday
590,2018-08-14,27,2018,14,8,August,1,Tuesday
510,2019-04-04,34,2019,4,4,April,3,Thursday

In [36]:
# Is weekened?

date['day_is_weekened'] = np.where(date['date_dow_name'].isin(['Saturday','Sunday']),1,0)

date.sample(3)

,date,orders,date_year,date_day,date_month_num,date_month_name,date_dayofweek,date_dow_name,day_is_weekened
510,2019-04-04,34,2019,4,4,April,3,Thursday,0
331,2019-10-21,1,2019,21,10,October,0,Monday,0
176,2018-12-16,8,2018,16,12,December,6,Sunday,1

In [41]:
# Extract week of year 
date['date_week'] = date['date'].dt.isocalendar().week

date.sample(5)

,date,orders,date_year,date_day,date_month_num,date_month_name,date_dayofweek,date_dow_name,day_is_weekened,date_week
464,2018-09-26,1,2018,26,9,September,2,Wednesday,0,39
877,2018-11-30,7,2018,30,11,November,4,Friday,0,48
820,2019-07-27,2,2019,27,7,July,5,Saturday,1,30
147,2019-12-09,139,2019,9,12,December,0,Monday,0,50
752,2019-06-21,12,2019,21,6,June,4,Friday,0,25

In [43]:
# Extract Quarter
date['date_quarter'] = date['date'].dt.quarter

date.sample(3)

,date,orders,date_year,date_day,date_month_num,date_month_name,date_dayofweek,date_dow_name,day_is_weekened,date_week,date_quarter
64,2019-06-01,5,2019,1,6,June,5,Saturday,1,22,2
146,2019-12-13,1,2019,13,12,December,4,Friday,0,50,4
954,2019-06-21,31,2019,21,6,June,4,Friday,0,25,2

In [47]:
# Extract Semester
date['date_semerter'] = np.where(date['date_quarter'].isin([1,2]),1,2)

date.sample(3)

,date,orders,date_year,date_day,date_month_num,date_month_name,date_dayofweek,date_dow_name,day_is_weekened,date_week,date_quarter,date_semerter
339,2019-12-05,1,2019,5,12,December,3,Thursday,0,49,4,2
770,2018-09-10,1,2018,10,9,September,0,Monday,0,37,3,2
632,2018-11-22,1,2018,22,11,November,3,Thursday,0,47,4,2

# Extract time elapse between dates

In [51]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2025, 10, 12, 0, 52, 23, 776885)

In [52]:
today - date['date']

0     2133 days 00:52:23.776885
1     2615 days 00:52:23.776885
2     2546 days 00:52:23.776885
3     2248 days 00:52:23.776885
4     2471 days 00:52:23.776885
                 ...
995   2561 days 00:52:23.776885
996   2502 days 00:52:23.776885
997   2350 days 00:52:23.776885
998   2415 days 00:52:23.776885
999   2189 days 00:52:23.776885
Name: date, Length: 1000, dtype: timedelta64[ns]

In [67]:
year_passed = (today - date['date']).dt.days
year_passed

0      2133
1      2615
2      2546
3      2248
4      2471
       ...
995    2561
996    2502
997    2350
998    2415
999    2189
Name: date, Length: 1000, dtype: int64

In [69]:
month_passed = ((today.year - date['date'].dt.year) * 12 + today.month - date['date'].dt.month)
month_passed

0      70
1      86
2      84
3      74
4      81
       ..
995    84
996    82
997    77
998    79
999    72
Name: date, Length: 1000, dtype: int32

# Working With Time

In [70]:
# Convert to datetime Format

time['date'] = pd.to_datetime(time['date'])

In [71]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [75]:
# Extract time part

time['time'] = time['date'].dt.time

time.sample(3)

,date,msg,time
726,2012-07-19 01:46:00,. привет парни. Я парень хочу сейчас очень пив...,01:46:00
45,2012-05-29 00:28:00,П26 ищу женщину.Хотелось бы старше.Днепр.05013...,00:28:00
518,2013-09-19 23:19:00,КисяПереживаюЧеловекВоВторникНеПозвонилЗавтраН...,23:19:00

In [77]:
time['hours'] = time['date'].dt.hour
time['minutes'] = time['date'].dt.minute
time['seconds'] = time['date'].dt.second

time.sample(3)

,date,msg,time,hours,minutes,seconds
332,2012-11-20 00:57:00,настя саша,00:57:00,0,57,0
89,2014-01-12 23:35:00,М45 ИЩУ ПОКОРНУЮ СТОЙНУЮ УХОЖЕНУЮ РАБУ 06389...,23:35:00,23,35,0
519,2015-01-24 22:51:00,Познакомлюсь с девушкой женщиной с днепра 0973...,22:51:00,22,51,0

In [78]:
# Time Difference

today - time['date']

0     4319 days 00:02:23.776885
1     4183 days 01:12:23.776885
2     4669 days 00:31:23.776885
3     3971 days 00:21:23.776885
4     4368 days 01:41:23.776885
                 ...
995   4958 days 00:02:23.776885
996   4279 days 01:38:23.776885
997   4744 days 01:15:23.776885
998   4860 days 01:18:23.776885
999   4132 days 01:27:23.776885
Name: date, Length: 1000, dtype: timedelta64[ns]

In [79]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.731617e+08
1      3.614155e+08
2      4.034035e+08
3      3.430957e+08
4      3.774013e+08
           ...
995    4.283713e+08
996    3.697115e+08
997    4.098861e+08
998    4.199087e+08
999    3.570100e+08
Name: date, Length: 1000, dtype: float64

In [80]:
# In minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.219362e+06
1      6.023592e+06
2      6.723391e+06
3      5.718261e+06
4      6.290021e+06
           ...
995    7.139522e+06
996    6.161858e+06
997    6.831435e+06
998    6.998478e+06
999    5.950167e+06
Name: date, Length: 1000, dtype: float64

In [81]:
# In hours

(today - time['date'])/np.timedelta64(1,'h')

0      103656.039938
1      100393.206605
2      112056.523271
3       95304.356605
4      104833.689938
           ...
995    118992.039938
996    102697.639938
997    113857.256605
998    116641.306605
999     99169.456605
Name: date, Length: 1000, dtype: float64