In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')

In [44]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
x=df[['Pclass','Age']]

In [9]:
y =  df['Survived']

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(x, y ,
                                                    test_size=0.3,
                                                    random_state=0)

In [48]:
X_train['Age']=X_train['Age'].fillna(29)

In [61]:
X_test['Age']=X_test['Age'].fillna(29)

In [62]:
 from sklearn.preprocessing import StandardScaler

In [63]:
scaler= StandardScaler()

scaler.fit(X_train)

x_train_scaled= scaler.transform(X_train)
x_test_scaled= scaler.transform(X_test)

In [64]:
X_train

     Pclass   Age
857       1  51.0
52        1  49.0
386       3   1.0
124       1  54.0
578       3  29.0
..      ...   ...
835       1  39.0
192       3  19.0
629       3  29.0
559       3  36.0
684       2  60.0

[623 rows x 2 columns]

In [65]:
x_train_scaled

array([[-1.5325562 ,  1.63377655],
       [-1.5325562 ,  1.48009931],
       [ 0.84844757, -2.20815449],
       ...,
       [ 0.84844757, -0.05667311],
       [ 0.84844757,  0.48119724],
       [-0.34205431,  2.32532414]])

In [66]:
x_train_scaled=pd.DataFrame(x_train_scaled,columns=X_train.columns)
x_test_scaled=pd.DataFrame(x_test_scaled,columns=X_test.columns)

In [67]:
np.round(X_train.describe(),1)

       Pclass    Age
count   623.0  623.0
mean      2.3   29.7
std       0.8   13.0
min       1.0    0.7
25%       1.5   23.0
50%       3.0   29.0
75%       3.0   36.0
max       3.0   80.0

In [68]:
np.round(x_train_scaled.describe(),1)

       Pclass    Age
count   623.0  623.0
mean      0.0    0.0
std       1.0    1.0
min      -1.5   -2.2
25%      -0.9   -0.5
50%       0.8   -0.1
75%       0.8    0.5
max       0.8    3.9

In [69]:
from sklearn.linear_model import LogisticRegression

In [70]:
lr= LogisticRegression()
lr_scaled= LogisticRegression()

In [71]:
lr.fit(X_train,y_train)
lr_scaled.fit(x_train_scaled,y_train)

LogisticRegression()

In [73]:
y_pred=lr.predict(X_test)
y_pred_scaled=lr_scaled.predict(x_test_scaled)

In [75]:
from sklearn.metrics import accuracy_score

In [76]:
print("actual",accuracy_score(y_test,y_pred))
print("scaled",accuracy_score(y_test,y_pred_scaled))

actual 0.7126865671641791
scaled 0.7126865671641791