In [2]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.model_selection import GridSearchCV

In [3]:
df = pd.read_csv("house_prices.csv")

In [4]:
df.head()

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,GarageCars,GarageArea,PoolArea,SalePrice
0,65.0,8450,7,5,2003,2,548,0,208500
1,80.0,9600,6,8,1976,2,460,0,181500
2,68.0,11250,7,5,2001,2,608,0,223500
3,60.0,9550,7,5,1915,3,642,0,140000
4,84.0,14260,8,5,2000,3,836,0,250000

In [5]:
df.shape

(1460, 9)

In [6]:
df.isnull().sum()

LotFrontage    259
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
GarageCars       0
GarageArea       0
PoolArea         0
SalePrice        0
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
X = df.iloc[:,0:8]
y = df.iloc[:,8]

In [9]:
X.head()

,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,GarageCars,GarageArea,PoolArea
0,65.0,8450,7,5,2003,2,548,0
1,80.0,9600,6,8,1976,2,460,0
2,68.0,11250,7,5,2001,2,608,0
3,60.0,9550,7,5,1915,3,642,0
4,84.0,14260,8,5,2000,3,836,0

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [11]:
drt = DecisionTreeRegressor(criterion = 'friedman_mse', max_depth=5)

In [12]:
drt.fit(X_train,y_train)

DecisionTreeRegressor(criterion='friedman_mse', max_depth=5)

In [13]:
y_pred = drt.predict(X_test)

In [14]:
r2_score(y_test,y_pred)

0.7030240462598993

# Feature Importancea

In [15]:
for importance, name in sorted(zip(drt.feature_importances_, X_train.columns),reverse=True):
  print (name, importance)

OverallQual 0.8134216235944113
GarageCars 0.057675922175403384
LotArea 0.0397223320608579
LotFrontage 0.029932106896578624
PoolArea 0.027249912823316846
YearBuilt 0.016336091695976395
GarageArea 0.01566201075345565
OverallCond 0.0