In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('bmw.csv')

In [3]:
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0

# feature Construction

In [5]:
df['Grand_Total'] = df['price'] + df['tax']

In [6]:
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,Grand_Total
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0,11325
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0,27145
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0,16160
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5,12895
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0,14660

# Feature Splitting

In [13]:
df['Car_Type'] = df['mileage']
df['Car_Type'].loc[df['mileage'] <= 1000] = 'Not Too Old'
df['Car_Type'].loc[df['mileage'] > 1000] = 'Old'
df['Car_Type'].loc[df['mileage'] <= 10] = 'New'

C:\Users\Saqib Ali\AppData\Local\Temp\ipykernel_4704\1988886765.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Car_Type'].loc[df['mileage'] <= 1000] = 'Not Too Old'
C:\Users\Saqib Ali\AppData\Local\Temp\ipykernel_4704\1988886765.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Car_Type'].loc[df['mileage'] <= 1000] = 'Not Too Old'
C:\Users\Saqib Ali\AppData\Local\Temp\ipykernel_4704\1988886765.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Not Too Old' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df['Car_Type'].loc[df['mileage'] <= 1000] = 'Not Too Old'
C:\Users\Saqib Ali\AppData\Local\Temp\ipykernel_4704\1988886765.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Car_Type'].loc[df['mileage'] > 1000] = 'Old'
C:\Users\Saqib Ali\AppData\Local\Temp\ipykernel_4704\1988886765.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Car_Type'].loc[df['mileage'] <= 10] = 'New'

In [15]:
df.sample(5)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,Grand_Total,Car_Type
7522,3 Series,2014,11750,Automatic,92000,Diesel,125,60.1,2.0,11875,Old
10098,5 Series,2017,16400,Automatic,67287,Diesel,20,68.9,2.0,16420,Old
8074,5 Series,2016,14499,Automatic,35644,Diesel,20,68.9,2.0,14519,Old
6887,5 Series,2019,34995,Semi-Auto,102,Petrol,145,50.4,2.0,35140,Not Too Old
557,X3,2013,14000,Semi-Auto,47111,Diesel,160,50.4,2.0,14160,Old