In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
df = pd.read_csv('used_car_listings.csv')

In [13]:
df.head()

,listing_id,vin,make,model,year,trim,body_type,fuel_type,transmission,mileage,price,condition,location,seller_type,features
0,1,9M6LF68V634LY2252,Tesla,Model 3,2019,NaN,Coupe,Electric,Manual,46134,19919.0,good,"New Lindsey, GA, US",Dealer,"Alloy Wheels, Android Auto, Apple CarPlay, Fog..."
1,2,1S0ZCY536BSCY2864,Nissan,Rogue,2024,LT,Sedan,Hybrid,Automatic,16109,19480.0,good,"Pughtown, CO, US",Dealer,"Alloy Wheels, Android Auto, Lane Keep Assist, ..."
2,3,YFB625BN0RTMZ5590,Hyundai,i20,2018,XLE,Crossover,Petrol,Automatic,173239,4556.0,good,"Satna, HR, India",Dealer,"Alloy Wheels, Bluetooth, Panoramic Roof, Sunroof"
3,4,CPMZ4RFN5WYL37096,Kia,Sportage,2023,EX,Hatchback,Diesel,CVT,36810,11536.0,fair,"山武市, Osaka, Japan",Certified Pre-Owned,"Alloy Wheels, Bluetooth, Keyless Entry, Naviga..."
4,5,4PJZG3MV6D9365673,Kia,Seltos,2020,Trend,Pickup,Diesel,Automatic,87749,14098.0,good,"長生郡長生村, Osaka, Japan",Certified Pre-Owned,"Apple CarPlay, Backup Camera, Bluetooth, Heate..."

In [15]:
df.isnull().mean()*100

listing_id       0.000000
vin              0.000000
make             0.000000
model            0.000000
year             0.000000
trim            11.798839
body_type        0.000000
fuel_type        0.000000
transmission     0.000000
mileage          0.000000
price            0.000000
condition        2.224371
location         0.000000
seller_type      0.000000
features         7.301741
dtype: float64

In [18]:
cols = [var for var in df.columns if df[var].isnull().mean()*100 < 10 and df[var].isnull().mean()*100 > 0]
cols

['condition', 'features']

In [19]:
len(df[cols].dropna()) / len(df)

0.9076402321083172

In [21]:
new_df = df[cols].dropna()
df.shape, new_df.shape

((2068, 15), (1877, 2))

In [22]:
temp = pd.concat([
    df['condition'].value_counts() / len(df),
    new_df['condition'].value_counts() / len(new_df)
],axis=1)

temp.columns= ['original','CCA']

temp

           original       CCA
condition
good       0.394584  0.404901
excellent  0.294487  0.301012
fair       0.174565  0.179542
like new   0.048356  0.049547
salvage    0.044971  0.044219
new        0.020793  0.020778

In [23]:
temp = pd.concat([
    df['features'].value_counts() / len(df),
    new_df['features'].value_counts() / len(new_df)
],axis=1)

temp.columns= ['original','CCA']

temp

                                                    original       CCA
features
LED Headlights, Leather Seats, Navigation, Pano...  0.000967  0.001066
Alloy Wheels, Android Auto, Backup Camera, Vent...  0.000967  0.001066
Bluetooth, Heated Seats, Panoramic Roof, Ventil...  0.000967  0.001066
Bluetooth, Leather Seats, Navigation, Push Butt...  0.000967  0.001066
Blind Spot Monitor, Bluetooth, Heated Seats, La...  0.000967  0.001066
...                                                      ...       ...
Adaptive Cruise Control, Keyless Entry, Leather...  0.000484  0.000533
Adaptive Cruise Control, Blind Spot Monitor, Bl...  0.000484  0.000533
Adaptive Cruise Control, Android Auto, Apple Ca...  0.000484  0.000533
Adaptive Cruise Control, Apple CarPlay, Blind S...  0.000484  0.000533
Adaptive Cruise Control, Android Auto, Apple Ca...  0.000484  0.000533

[1903 rows x 2 columns]