In [2]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv('placement.csv')

In [16]:
df.head()

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [5]:
df = df.drop(columns=['State'])

In [6]:
df.head()

   R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [22]:
X = df.iloc[:,[0]]
y = df.iloc[:,-1]

In [18]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score

In [19]:
lr = LinearRegression()
dt = DecisionTreeRegressor()
svr = SVR()

In [20]:
estimators = [('lr',lr),('dt',dt),('svr',svr)]

In [23]:
for estimator in estimators:
  scores = cross_val_score(estimator[1],X,y,scoring='r2',cv=10)
  print(estimator[0],np.round(np.mean(scores),2))

lr 0.74
dt 0.53
svr 0.73

In [24]:
from sklearn.ensemble import VotingRegressor

In [25]:
vr = VotingRegressor(estimators)
scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
print("Voting Regressor",np.round(np.mean(scores),2))

Voting Regressor 0.72

In [26]:
for i in range(1,4):
  for j in range(1,4):
    for k in range(1,4):
      vr = VotingRegressor(estimators,weights=[i,j,k])
      scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
      print("For i={},j={},k={}".format(i,j,k),np.round(np.mean(scores),2))

For i=1,j=1,k=1 0.72
For i=1,j=1,k=2 0.73
For i=1,j=1,k=3 0.73
For i=1,j=2,k=1 0.69
For i=1,j=2,k=2 0.71
For i=1,j=2,k=3 0.71
For i=1,j=3,k=1 0.66
For i=1,j=3,k=2 0.69
For i=1,j=3,k=3 0.7
For i=2,j=1,k=1 0.73
For i=2,j=1,k=2 0.73
For i=2,j=1,k=3 0.73
For i=2,j=2,k=1 0.71
For i=2,j=2,k=2 0.72
For i=2,j=2,k=3 0.72
For i=2,j=3,k=1 0.69
For i=2,j=3,k=2 0.7
For i=2,j=3,k=3 0.71
For i=3,j=1,k=1 0.73
For i=3,j=1,k=2 0.74
For i=3,j=1,k=3 0.74
For i=3,j=2,k=1 0.72
For i=3,j=2,k=2 0.72
For i=3,j=2,k=3 0.73
For i=3,j=3,k=1 0.7
For i=3,j=3,k=2 0.71
For i=3,j=3,k=3 0.72

## using the same algorithm

In [27]:
dt1 = DecisionTreeRegressor(max_depth=1)
dt2 = DecisionTreeRegressor(max_depth=3)
dt3 = DecisionTreeRegressor(max_depth=5)
dt4 = DecisionTreeRegressor(max_depth=7)
dt5 = DecisionTreeRegressor(max_depth=None)

In [28]:
estimators = [('dt1',dt1),('dt2',dt2),('dt3',dt3),('dt4',dt4),('dt5',dt5)]

In [29]:
for estimator in estimators:
  scores = cross_val_score(estimator[1],X,y,scoring='r2',cv=10)
  print(estimator[0],np.round(np.mean(scores),2))

dt1 0.32
dt2 0.67
dt3 0.61
dt4 0.57
dt5 0.53

In [30]:
vr = VotingRegressor(estimators)
scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
print("Voting Regressor",np.round(np.mean(scores),2))

Voting Regressor 0.64