In [18]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [19]:
df = pd.read_csv('house-train.csv',usecols=['GarageQual','FireplaceQu','SalePrice'])

In [20]:
df.head()

  FireplaceQu GarageQual  SalePrice
0         NaN         TA     208500
1          TA         TA     181500
2          TA         TA     223500
3          Gd         TA     140000
4          TA         TA     250000

In [21]:
df['GarageQual'].value_counts()

GarageQual
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64

In [22]:
df.isnull().sum()

FireplaceQu    690
GarageQual      81
SalePrice        0
dtype: int64

In [23]:
x = df.drop(columns=['SalePrice'])
y = df['SalePrice']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [24]:
x_train.head()

     FireplaceQu GarageQual
455           TA         TA
863          NaN         TA
504           Fa         TA
1413          Gd         TA
1389          Gd         TA

In [26]:
oe = OrdinalEncoder()

x_train = oe.fit_transform(x_train)
x_test = oe.transform(x_test)

In [27]:
knn = KNNImputer(n_neighbors=1,weights='distance')

x_train_trf = knn.fit_transform(x_train)
x_test_trf = knn.transform(x_test)

In [28]:
lr = LogisticRegression()

lr.fit(x_train_trf,y_train)

y_pred = lr.predict(x_test_trf)

accuracy_score(y_test,y_pred)

E:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.010273972602739725

In [29]:
# Comparision with Simple Imputer --> mean

si = SimpleImputer()

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [30]:
lr = LogisticRegression()

lr.fit(x_train_trf2,y_train)

y_pred = lr.predict(x_test_trf2)

accuracy_score(y_test,y_pred)

E:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.0136986301369863