In [6]:
import numpy as np
import pandas as pd

import plotly.express as px
import plotly.graph_objects as po

from sklearn.metrics import r2_score

In [13]:
df = pd.read_csv('50_Startups.csv').drop(columns=['State'])

In [14]:
df.head()

   R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [15]:
df.shape

(50, 4)

In [21]:
x = df.iloc[:,0:3]
y = df['Profit']

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=3)

In [23]:
x_train.head()

    R&D Spend  Administration  Marketing Spend
36   28663.76       127056.21        201126.82
23   67532.53       105751.03        304768.73
37   44069.95        51283.14        197029.42
18   91749.16       114175.79        294919.57
4   142107.34        91391.77        366168.42

In [24]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
r2_score(y_test,y_pred)

0.946980087531592

In [25]:
lr.coef_

array([ 0.82221292, -0.08474077,  0.02170857])

In [26]:
lr.intercept_

np.float64(56838.960438274866)