In [22]:
import pandas as pd

In [23]:
df = pd.read_csv("restaurant_orders.csv")

# How big is the data

In [24]:
df.shape

(500, 8)

# How does the data look like?

In [25]:
df.sample(5)

,Order ID,Customer Name,Food Item,Category,Quantity,Price,Payment Method,Order Time
139,8382,Andrea Reynolds,Pizza,Main,3,6.65,Credit Card,2025-07-29 07:04:35
1,3082,Brandon Myers,Brownie,Dessert,4,17.27,Debit Card,2025-06-08 10:57:47
162,5550,Laura Wheeler,Pizza,Main,3,24.52,Debit Card,2025-07-28 21:27:09
312,4937,Caleb Little,Cake,Dessert,5,16.07,Credit Card,2025-02-15 00:38:57
453,9450,Pamela Moore,Salad,Starter,3,22.03,Online Payment,2025-07-14 12:55:33

# What is the dtat type of cols?

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        500 non-null    int64
 1   Customer Name   500 non-null    object
 2   Food Item       500 non-null    object
 3   Category        500 non-null    object
 4   Quantity        500 non-null    int64
 5   Price           500 non-null    float64
 6   Payment Method  500 non-null    object
 7   Order Time      500 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 31.4+ KB

# Are there any missing values?

In [27]:
df.isnull().sum()

Order ID          0
Customer Name     0
Food Item         0
Category          0
Quantity          0
Price             0
Payment Method    0
Order Time        0
dtype: int64

# How does the data look mathematically?

In [28]:
df.describe()

          Order ID    Quantity       Price
count   500.000000  500.000000  500.000000
mean   5683.296000    3.030000   13.197180
std    2599.688068    1.474261    6.685852
min    1055.000000    1.000000    2.060000
25%    3342.000000    2.000000    7.280000
50%    5762.000000    3.000000   13.305000
75%    7945.000000    4.000000   19.080000
max    9997.000000    5.000000   24.990000

# Are there duplicate values?

### Drop these dulpicate values by pandas drop.duplicate()

In [29]:
df.duplicated().sum()

0

# What is the correlation between cols?

In [30]:
df.select_dtypes(include=["float64","int64"]).corr()

          Order ID  Quantity     Price
Order ID  1.000000  0.039302 -0.041121
Quantity  0.039302  1.000000  0.005980
Price    -0.041121  0.005980  1.000000