In [1]:
import pandas as pd

# JSON

In [2]:
pd.read_json("https://raw.githubusercontent.com/Vaishali91tanwar/ETL-Project/master/US_category_id.json")

,kind,etag,items
0,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
1,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
2,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
3,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
4,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
5,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
6,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
7,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
8,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
9,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
10,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
11,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
12,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
13,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
14,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
15,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
16,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
17,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
18,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
19,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
20,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
21,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
22,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
23,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
24,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
25,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
26,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
27,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
28,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
29,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
30,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
31,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."

In [3]:
pd.read_json('housing_price_dataset.json')

,property_id,city,locality,locality_tier,property_type,bhk,bathrooms,balconies,built_up_area,carpet_area,...,power_backup,lift_available,maintenance_fee_monthly,distance_to_city_center_km,distance_to_metro_km,nearby_schools,nearby_hospitals,transaction_type,price_in_lakhs,price_category
0,PROP-000001,Bangalore,HSR Layout,Standard,Apartment,4,4,1,1570,1361,...,1,0,3094,11.6,3.5,3,1,New,102.34,Low
1,PROP-000002,Mumbai,Powai,Standard,Row House,2,1,1,908,778,...,1,1,3893,24.2,1.3,3,2,Resale,71.48,Low
2,PROP-000003,Bangalore,Indiranagar,Premium,Independent House,3,3,2,1784,1568,...,1,1,7038,5.0,0.1,2,1,Resale,245.57,High
3,PROP-000004,Mumbai,Powai,Standard,Independent House,4,4,2,2318,2011,...,0,1,3569,11.9,7.9,2,0,New,122.95,Low
4,PROP-000005,Bangalore,Electronic City,Standard,Apartment,3,4,2,988,840,...,1,1,2628,11.4,7.2,1,0,Resale,64.71,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,PROP-049996,Mumbai,Andheri,Standard,Independent House,2,2,3,1111,936,...,0,1,2297,11.6,0.2,3,2,Resale,88.00,Low
49996,PROP-049997,Bangalore,Koramangala,Premium,Apartment,3,3,1,1191,1009,...,1,1,1799,7.2,10.7,4,1,Resale,189.36,Low
49997,PROP-049998,Bangalore,Indiranagar,Premium,Independent House,4,4,3,2133,1823,...,1,0,7263,8.0,1.6,6,1,Resale,464.59,High
49998,PROP-049999,Bangalore,Indiranagar,Premium,Villa,2,2,1,1532,1345,...,1,1,6306,5.9,4.6,7,3,New,294.31,High
49999,PROP-050000,Bangalore,Electronic City,Standard,Penthouse,5,5,4,2661,2236,...,1,0,5617,11.5,4.5,1,1,Resale,186.87,Low

# SQL

In [4]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     - ------------------------------------- 0.5/11.9 MB 397.3 kB/s eta 0:00:29
     - ------------------------------------- 0.5/11.9 MB 397.3 kB/s eta 0:00:29
     - ------------------------------------- 0.5/11.9 MB 397.3 kB/s eta 0:00:29
     - ------------------------------------- 0.5/11.9 MB 397.3 kB/s eta 0:00:29
     -- ------------------------------------ 0.8/11.9 MB 370.0 kB/s eta 0:00:30
     --- ----------------------------------- 1.0/11.9 MB 458.1 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.9 MB 458.1 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.9 MB 458.1 kB/s eta 0:00:24
     ---- ---------------------------------- 1.3/11.9 MB 447.1 kB/s eta 0:00:24
     ---- ---------------------------------- 1.3/11.9 MB 447.1 kB/s eta 0:00:24
     ---- ---------------------------------- 1.3/11.9 MB 447.1 kB/s eta 0:00:24
     ----- --------------------------------- 1.6/11.9 MB 459.0 kB/s eta 0:00:23
     ----- --------------------------------- 1.6/11.9 MB 459.0 kB/s eta 0:00:23
     ------ -------------------------------- 1.8/11.9 MB 465.5 kB/s eta 0:00:22
     ------ -------------------------------- 1.8/11.9 MB 465.5 kB/s eta 0:00:22
     ------ -------------------------------- 1.8/11.9 MB 465.5 kB/s eta 0:00:22
     ------ -------------------------------- 2.1/11.9 MB 466.3 kB/s eta 0:00:21
     ------ -------------------------------- 2.1/11.9 MB 466.3 kB/s eta 0:00:21
     ------ -------------------------------- 2.1/11.9 MB 466.3 kB/s eta 0:00:21
     ------- ------------------------------- 2.4/11.9 MB 469.1 kB/s eta 0:00:21
     ------- ------------------------------- 2.4/11.9 MB 469.1 kB/s eta 0:00:21
     -------- ------------------------------ 2.6/11.9 MB 470.0 kB/s eta 0:00:20
     -------- ------------------------------ 2.6/11.9 MB 470.0 kB/s eta 0:00:20
     -------- ------------------------------ 2.6/11.9 MB 470.0 kB/s eta 0:00:20
     --------- ----------------------------- 2.9/11.9 MB 471.5 kB/s eta 0:00:20
     --------- ----------------------------- 2.9/11.9 MB 471.5 kB/s eta 0:00:20
     ---------- ---------------------------- 3.1/11.9 MB 472.6 kB/s eta 0:00:19
     ---------- ---------------------------- 3.1/11.9 MB 472.6 kB/s eta 0:00:19
     ---------- ---------------------------- 3.1/11.9 MB 472.6 kB/s eta 0:00:19
     ----------- --------------------------- 3.4/11.9 MB 473.7 kB/s eta 0:00:18
     ----------- --------------------------- 3.4/11.9 MB 473.7 kB/s eta 0:00:18
     ----------- --------------------------- 3.4/11.9 MB 473.7 kB/s eta 0:00:18
     ------------ -------------------------- 3.7/11.9 MB 472.5 kB/s eta 0:00:18
     ------------ -------------------------- 3.7/11.9 MB 472.5 kB/s eta 0:00:18
     ------------ -------------------------- 3.9/11.9 MB 474.1 kB/s eta 0:00:17
     ------------ -------------------------- 3.9/11.9 MB 474.1 kB/s eta 0:00:17
     ------------ -------------------------- 3.9/11.9 MB 474.1 kB/s eta 0:00:17
     ------------- ------------------------- 4.2/11.9 MB 477.2 kB/s eta 0:00:17
     ------------- ------------------------- 4.2/11.9 MB 477.2 kB/s eta 0:00:17
     -------------- ------------------------ 4.5/11.9 MB 477.4 kB/s eta 0:00:16
     -------------- ------------------------ 4.5/11.9 MB 477.4 kB/s eta 0:00:16
     -------------- ------------------------ 4.5/11.9 MB 477.4 kB/s eta 0:00:16
     --------------- ----------------------- 4.7/11.9 MB 478.9 kB/s eta 0:00:15
     --------------- ----------------------- 4.7/11.9 MB 478.9 kB/s eta 0:00:15
     --------------- ----------------------- 4.7/11.9 MB 478.9 kB/s eta 0:00:15
     ---------------- ---------------------- 5.0/11.9 MB 468.5 kB/s eta 0:00:15
     ---------------- ---------------------- 5.0/11.9 MB 468.5 kB/s eta 0:00:15
     ----------------- --------------------- 5.2/11.9 MB 476.2 kB/s eta 0:00:14
     ----------------- --------------------- 5.2/11.9 MB 476.2 kB/s eta 0:00:14
     ------------------ -------------------- 5.5/11.9 MB 477.9 kB/s eta 0:00:14
     ------------------ -------------------- 5.5/11.9 MB 477.9 kB/s eta 0:00:14
     ------------------ -------------------- 5.5/11.9 MB 477.9 kB/s eta 0:00:14
     ------------------ -------------------- 5.8/11.9 MB 477.8 kB/s eta 0:00:13
     ------------------ -------------------- 5.8/11.9 MB 477.8 kB/s eta 0:00:13
     ------------------ -------------------- 5.8/11.9 MB 477.8 kB/s eta 0:00:13
     ------------------- ------------------- 6.0/11.9 MB 477.8 kB/s eta 0:00:13
     ------------------- ------------------- 6.0/11.9 MB 477.8 kB/s eta 0:00:13
     -------------------- ------------------ 6.3/11.9 MB 476.8 kB/s eta 0:00:12
     -------------------- ------------------ 6.3/11.9 MB 476.8 kB/s eta 0:00:12
     -------------------- ------------------ 6.3/11.9 MB 476.8 kB/s eta 0:00:12
     --------------------- ----------------- 6.6/11.9 MB 478.5 kB/s eta 0:00:12
     --------------------- ----------------- 6.6/11.9 MB 478.5 kB/s eta 0:00:12
     ---------------------- ---------------- 6.8/11.9 MB 478.6 kB/s eta 0:00:11
     ---------------------- ---------------- 6.8/11.9 MB 478.6 kB/s eta 0:00:11
     ---------------------- ---------------- 6.8/11.9 MB 478.6 kB/s eta 0:00:11
     ----------------------- --------------- 7.1/11.9 MB 478.7 kB/s eta 0:00:10
     ----------------------- --------------- 7.1/11.9 MB 478.7 kB/s eta 0:00:10
     ------------------------ -------------- 7.3/11.9 MB 478.3 kB/s eta 0:00:10
     ------------------------ -------------- 7.3/11.9 MB 478.3 kB/s eta 0:00:10
     ------------------------ -------------- 7.3/11.9 MB 478.3 kB/s eta 0:00:10
     ------------------------- ------------- 7.6/11.9 MB 478.7 kB/s eta 0:00:09
     ------------------------- ------------- 7.6/11.9 MB 478.7 kB/s eta 0:00:09
     ------------------------- ------------- 7.6/11.9 MB 478.7 kB/s eta 0:00:09
     ------------------------- ------------- 7.9/11.9 MB 478.6 kB/s eta 0:00:09
     ------------------------- ------------- 7.9/11.9 MB 478.6 kB/s eta 0:00:09
     -------------------------- ------------ 8.1/11.9 MB 479.0 kB/s eta 0:00:08
     -------------------------- ------------ 8.1/11.9 MB 479.0 kB/s eta 0:00:08
     -------------------------- ------------ 8.1/11.9 MB 479.0 kB/s eta 0:00:08
     --------------------------- ----------- 8.4/11.9 MB 479.1 kB/s eta 0:00:08
     --------------------------- ----------- 8.4/11.9 MB 479.1 kB/s eta 0:00:08
     ---------------------------- ---------- 8.7/11.9 MB 480.1 kB/s eta 0:00:07
     ---------------------------- ---------- 8.7/11.9 MB 480.1 kB/s eta 0:00:07
     ---------------------------- ---------- 8.7/11.9 MB 480.1 kB/s eta 0:00:07
     ----------------------------- --------- 8.9/11.9 MB 478.9 kB/s eta 0:00:07
     ----------------------------- --------- 8.9/11.9 MB 478.9 kB/s eta 0:00:07
     ----------------------------- --------- 8.9/11.9 MB 478.9 kB/s eta 0:00:07
     ------------------------------ -------- 9.2/11.9 MB 479.7 kB/s eta 0:00:06
     ------------------------------ -------- 9.2/11.9 MB 479.7 kB/s eta 0:00:06
     ------------------------------- ------- 9.4/11.9 MB 480.7 kB/s eta 0:00:06
     ------------------------------- ------- 9.4/11.9 MB 480.7 kB/s eta 0:00:06
     ------------------------------- ------- 9.4/11.9 MB 480.7 kB/s eta 0:00:06
     ------------------------------- ------- 9.7/11.9 MB 479.0 kB/s eta 0:00:05
     ------------------------------- ------- 9.7/11.9 MB 479.0 kB/s eta 0:00:05
     ------------------------------- ------ 10.0/11.9 MB 480.3 kB/s eta 0:00:04
     ------------------------------- ------ 10.0/11.9 MB 480.3 kB/s eta 0:00:04
     ------------------------------- ------ 10.0/11.9 MB 480.3 kB/s eta 0:00:04
     -------------------------------- ----- 10.2/11.9 MB 480.3 kB/s eta 0:00:04
     -------------------------------- ----- 10.2/11.9 MB 480.3 kB/s eta 0:00:04
     --------------------------------- ---- 10.5/11.9 MB 479.7 kB/s eta 0:00:03
     --------------------------------- ---- 10.5/11.9 MB 479.7 kB/s eta 0:00:03
     --------------------------------- ---- 10.5/11.9 MB 479.7 kB/s eta 0:00:03
     --------------------------------- ---- 10.5/11.9 MB 479.7 kB/s eta 0:00:03
     ---------------------------------- --- 10.7/11.9 MB 476.9 kB/s eta 0:00:03
     ----------------------------------- -- 11.0/11.9 MB 480.2 kB/s eta 0:00:02
     ----------------------------------- -- 11.0/11.9 MB 480.2 kB/s eta 0:00:02
     ----------------------------------- -- 11.0/11.9 MB 480.2 kB/s eta 0:00:02
     ------------------------------------ - 11.3/11.9 MB 480.0 kB/s eta 0:00:02
     ------------------------------------ - 11.3/11.9 MB 480.0 kB/s eta 0:00:02
     ------------------------------------ - 11.5/11.9 MB 480.8 kB/s eta 0:00:01
     ------------------------------------ - 11.5/11.9 MB 480.8 kB/s eta 0:00:01
     ------------------------------------ - 11.5/11.9 MB 480.8 kB/s eta 0:00:01
     -------------------------------------  11.8/11.9 MB 481.0 kB/s eta 0:00:01
     -------------------------------------- 11.9/11.9 MB 479.9 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py): started
  Building wheel for mysql.connector (setup.py): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=247959 sha256=606bb7a4775562c723b5197c5e7c403aa396323527d9307b8939eb07c691cae2
  Stored in directory: c:\users\cccc\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

  DEPRECATION: Building 'mysql.connector' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'mysql.connector'. Discussion can be found at https://github.com/pypa/pip/issues/6334

In [5]:
import mysql.connector

In [7]:
conn = mysql.connector.Connect(host='localhost', user='root', password='', database='world')

In [8]:
df = pd.read_sql_query('select * from country', conn)

C:\Users\cccc\AppData\Local\Temp\ipykernel_10544\3805977493.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('select * from country', conn)

In [9]:
df.head()

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL