In [54]:
import numpy as np
import pandas as pd

In [55]:
df = pd.read_csv('ecommerce_dataset_10000.csv')

In [56]:
df.head()

,customer_id,first_name,last_name,gender,age_group,signup_date,country,product_id,product_name,category,quantity,unit_price,order_id,order_date,order_status,payment_method,rating,review_text,review_id,review_date
0,CUST2353,Erica,Oliver,Female,Teenagers,2022-06-29,Canada,PROD108,Fitbit Versa 3,Electronics,3,229,ORD10000,2023-07-13,Pending,Credit Card,2,good,REV20000,2025-06-06
1,CUST4463,Christopher,White,Male,Adults,2023-08-24,China,PROD103,Levi's Jeans,Apparel,4,59,ORD10001,2024-08-12,Pending,PayPal,2,average,REV20001,2023-08-05
2,CUST4512,Spencer,Foster,Male,Senior,2023-07-18,Germany,PROD111,Lego Star Wars Set,Toys,2,59,ORD10002,2024-08-04,Delivered,Cash on Delivery,5,good,REV20002,2023-01-03
3,CUST5711,Jessica,Harris,Male,Teenagers,2025-08-22,France,PROD107,Dyson Vacuum,Home & Kitchen,4,399,ORD10003,2025-05-23,Delivered,Cash on Delivery,2,very good,REV20003,2023-03-14
4,CUST1296,Amy,Johnson,Female,Teenagers,2021-03-23,Brazil,PROD105,Adidas Running Shoes,Apparel,1,110,ORD10004,2023-07-02,Returned,Cash on Delivery,1,very good,REV20004,2023-10-18

In [57]:
df = df[['age_group','category','quantity','unit_price','rating','review_text']]

In [58]:
df.shape

(10000, 6)

In [59]:
df.head()

   age_group        category  quantity  unit_price  rating review_text
0  Teenagers     Electronics         3         229       2        good
1     Adults         Apparel         4          59       2     average
2     Senior            Toys         2          59       5        good
3  Teenagers  Home & Kitchen         4         399       2   very good
4  Teenagers         Apparel         1         110       1   very good

In [60]:
transformed_df = df[['category','quantity','unit_price','rating']]

In [61]:
transformed_df.sample(5)

         category  quantity  unit_price  rating
462        Sports         4          25       1
2525  Electronics         3         229       3
5919      Apparel         3          59       3
1056  Electronics         1         199       5
6286      Apparel         4         120       5

In [62]:
test_df = df[['age_group','review_text']]

In [63]:
test_df.head()

   age_group review_text
0  Teenagers        good
1     Adults     average
2     Senior        good
3  Teenagers   very good
4  Teenagers   very good

In [64]:
test_df['review_text'].unique()

array(['good', 'average', 'very good', 'bad', 'very bad'], dtype=object)

# Ordinal Encoder

In [65]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Teenagers','Adults','Senior'],['very bad','bad','average','good','very good']])

oe.fit(test_df)

test_df_transformed = oe.transform(test_df)

In [66]:
test_df_transformed

array([[0., 3.],
       [1., 2.],
       [2., 3.],
       ...,
       [1., 2.],
       [0., 4.],
       [1., 4.]])

In [67]:
test_df_transformed.shape

(10000, 2)

In [68]:
test_df_transformed = pd.DataFrame(test_df_transformed, columns=test_df.columns)

In [69]:
test_df_transformed.head()

   age_group  review_text
0        0.0          3.0
1        1.0          2.0
2        2.0          3.0
3        0.0          4.0
4        0.0          4.0

# Concatenating back Ordinal Encoder transformed to Original Dataframe

In [70]:
transformed_df = pd.concat([transformed_df,test_df_transformed],axis=1)

In [71]:
transformed_df.head()

         category  quantity  unit_price  rating  age_group  review_text
0     Electronics         3         229       2        0.0          3.0
1         Apparel         4          59       2        1.0          2.0
2            Toys         2          59       5        2.0          3.0
3  Home & Kitchen         4         399       2        0.0          4.0
4         Apparel         1         110       1        0.0          4.0