In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("used_car_listings.csv")

# How Big is the data?

In [5]:
df.shape

(2068, 15)

# How does the data look like

In [6]:
df.sample(5)

,listing_id,vin,make,model,year,trim,body_type,fuel_type,transmission,mileage,price,condition,location,seller_type,features
1606,1607,LBGFHS8N63FSM9665,Mercedes-Benz,GLC,2017,NaN,Convertible,Hybrid,Automatic,196917,7070.0,good,"Chartier, BFC, France",Dealer,"Alloy Wheels, Android Auto, Blind Spot Monitor..."
167,168,W962WAKD3YP8E7280,Hyundai,Tucson,2015,Limited,Sedan,Diesel,AMT,221741,1856.0,good,"Chennai, KL, India",Dealer,"Backup Camera, Bluetooth, Heated Seats, Keyles..."
1933,1934,UUM24D500SPMY1649,Ford,Maverick,2015,NaN,MPV,Diesel,Manual,97556,3694.0,like new,"Johannesburg, MP, South Africa",Dealer,"Blind Spot Monitor, Fog Lights, Leather Seats,..."
1421,1422,93ASNNL69NVVP3608,Audi,A4,2018,Sport,Crossover,Petrol,Automatic,81470,8246.0,fair,"Christinaside, CA, US",Dealer,"Backup Camera, LED Headlights, Lane Keep Assis..."
595,596,03NRWUFC0AK4Y2393,Skoda,Slavia,2020,SE,Convertible,Petrol,Manual,60412,15957.0,new,"Elainebury, SCT, UK",Private Party,"Apple CarPlay, Backup Camera, Bluetooth, LED H..."

# What is the data type of cols?

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2068 entries, 0 to 2067
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   listing_id    2068 non-null   int64
 1   vin           2068 non-null   object
 2   make          2068 non-null   object
 3   model         2068 non-null   object
 4   year          2068 non-null   int64
 5   trim          1824 non-null   object
 6   body_type     2068 non-null   object
 7   fuel_type     2068 non-null   object
 8   transmission  2068 non-null   object
 9   mileage       2068 non-null   int64
 10  price         2068 non-null   float64
 11  condition     2022 non-null   object
 12  location      2068 non-null   object
 13  seller_type   2068 non-null   object
 14  features      1917 non-null   object
dtypes: float64(1), int64(3), object(11)
memory usage: 242.5+ KB

# Are there any missing values

In [8]:
df.isnull().sum()

listing_id        0
vin               0
make              0
model             0
year              0
trim            244
body_type         0
fuel_type         0
transmission      0
mileage           0
price             0
condition        46
location          0
seller_type       0
features        151
dtype: int64

# How does the data look mathematically

In [9]:
df.describe()

        listing_id         year        mileage         price
count  2068.000000  2068.000000    2068.000000   2068.000000
mean   1034.500000  2016.975822  115626.364603   9182.621857
std     597.124498     4.610981   80971.112603   9964.093618
min       1.000000  2005.000000       0.000000   1140.000000
25%     517.750000  2014.000000   57683.250000   2323.750000
50%    1034.500000  2017.000000   99212.000000   5448.500000
75%    1551.250000  2020.000000  159291.500000  11946.750000
max    2068.000000  2025.000000  418428.000000  72641.000000

# Are there duplicate values?

In [11]:
df.duplicated().sum()

0

# What is the correlation between cols?

In [15]:
df.select_dtypes(include=["int64","float64"]).corr()

            listing_id      year   mileage     price
listing_id    1.000000 -0.019230  0.013799 -0.009792
year         -0.019230  1.000000 -0.815206  0.750634
mileage       0.013799 -0.815206  1.000000 -0.642601
price        -0.009792  0.750634 -0.642601  1.000000